### ISSUE TITLE
"Unparsable" NotImplemementedError when getting values from variables

### ISSUE THREAD

**Issue by xmo-odoo** [asottile/setup-py-upgrade#16]
If setup.py gets setup() values from variables, the script blows up with a NotImplementedError:
```
Traceback (most recent call last):
  File "site-packages/setup_py_upgrade.py", line 125, in visit_Call
    value = ast.literal_eval(kwd.value)
  File "ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Name object at 0x7fdf99964e10>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup-py-upgrade", line 8, in <module>
    sys.exit(main())
  File "site-packages/setup_py_upgrade.py", line 167, in main
    visitor.visit(tree)
  File "ast.py", line 253, in visit
    return visitor(node)
  File "ast.py", line 261, in generic_visit
    self.visit(item)
  File "ast.py", line 253, in visit
    return visitor(node)
  File "ast.py", line 263, in generic_visit
    self.visit(value)
  File "ast.py", line 253, in visit
    return visitor(node)
  File "setup_py_upgrade.py", line 127, in visit_Call
    raise NotImplementedError(f'unparsable: {kwd.arg}=')
NotImplementedError: unparsable: version=
```
This probably isn't fully fixable as the variable could be a constant, or it might come from a separate python file, or even from reading some data from an external file.

**Comment by asottile** [comment]
yeah this is (intentionally) not implemented -- probably needs more of a mention in this section in the README: https://github.com/asottile/setup-py-upgrade#what-is-not-supported

there's currently parsing supported for converting this into `file:` though so if there's some obvious pattern that can be used then that's a possibility:

```python
with open('filename') as f:
    contents = f.read()

setup(varname=contents)
```

**Comment by asottile** [comment]
without seeing the `setup.py` I don't know what case your particular one falls into

**Comment by xmo-odoo** [comment]
> yeah this is (intentionally) not implemented -- probably needs more of a mention in this section in the README: https://github.com/asottile/setup-py-upgrade#what-is-not-supported

I think the most valuable would be a clearer error message (print key and reformatted name and indicate that non-literal values are not supported), it's possible to infer what happens from the traceback but it gives a bit of a pause and it's hardly pretty.

> without seeing the setup.py I don't know what case your particular one falls into

Much of the metadata is gotten from an other python file so it would be surprising for things to work in retrospect, I just ran the script to take a look.

**Comment by asottile** [comment]
I'm not sure what you expected 😆 would you like to submit a PR?

**Comment by wwuck** [comment]
I encountered this error too when I ran setup-py-upgrade on this simple setup.py file:
```python
from setuptools import setup

install_requirements = ['attrs']
setup(
    name='test',
    install_requires=install_requirements
)
```

Is this possible to fix at all, or is there some inherent limitation of python's ast module that makes it unfixable?

**Comment by asottile** [comment]
there's no reason to write a setup py like that, inline it and it'll get converted -- [see above](https://github.com/asottile/setup-py-upgrade/issues/16#issuecomment-553269832)

**Comment by asottile** [comment]
note that in the general case you're asking setup-py-upgrade to solve the halting problem, which is intractable

**Comment by wwuck** [comment]
Ok, thanks!
