### ISSUE TITLE
Stop using deprecated 'license_file' wheel option

### ISSUE THREAD

**Issue by mondeja** [asottile/setup-py-upgrade#50]
The keyword `license_file` [has been deprecated by wheel in v0.32](https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file) and the wheel's behaviour for discovering license files for autoincluding them is documented in the previous link. The logic for discover license files in wheel is [currently here](https://github.com/pypa/wheel/blob/0b29b695ae458450217552978ad3094ed06a16d7/src/wheel/bdist_wheel.py#L422-L433).

I suppose that the proposed solution should only render `license_files` when (1) a `license_file` is specified in `setup.py` but the path is not covered by wheel globs and (2) when a `license_files` is explicitly specified in `setup.py`.

**Comment by asottile** [comment]
see previous discussion: https://github.com/asottile/setup-cfg-fmt/issues/73
