### ISSUE TITLE
It breaks if I use `open().read()` as value of a field

### ISSUE THREAD

**Issue by lnxpy** [asottile/setup-py-upgrade#98]
Example:
```python
setup(
    ...
    long_description=open(...).read(),
    ...
)
```

```sh
NotImplementedError: unparsable: long_description=
```

It can't pars the `long_description` with that value. I think it should pars it to something like the following line in `setup.cfg`:

```ini
long_description = file: filename
```

**Comment by asottile** [comment]
your pattern leaks a file descriptor. there are certain patterns of code it detects but I don't think it should detect wrong things

**Comment by asottile** [comment]
it does if you use `open` correctly: https://github.com/asottile/setup-py-upgrade/blob/8be9148cd2b9e8a52aabfdceed8051d448ece5f9/tests/setup_py_upgrade_test.py#L30-L42
